hbb_make_zstdra: adapted to use different versions of zstd, updated zstd to 1.5.1,

diff --git a/extern-src/adapted_Makefile_zstd-mt b/extern-src/adapted_Makefile_zstd-mt
--- a/extern-src/adapted_Makefile_zstd-mt
+++ b/extern-src/adapted_Makefile_zstd-mt
@@ -1,14 +1,16 @@
 ##############################################################################
 # GNU Makefile for zstmt
-# /TR 2018-12-28
+# /TR 2020-10-16
 ##############################################################################
 
 # current versions we're using (tagged in their main repo)
-BRO_VER	= "v1.0.7"
+BRO_VER	= "v1.0.9"
 LIZ_VER	= "v1.0"
-LZ4_VER	= "v1.8.3"
+LZ4_VER	= "v1.9.2"
 LZ5_VER	= "v1.5"
-ZSTD_VER= "v1.4.4"
+ZSTD_VER= "v1.5.1"
+SNAP_VER= "v0.0.0"
+LZFSE_VER="lzfse-1.0"
 
 # uncomment, for cross compiling or windows binaries
 #WIN_LDFLAGS	= -lwinmm -lpsapi
@@ -25,6 +27,7 @@ CC	= $(CROSS)gcc
 RANLIB	= $(CROSS)ranlib
 STRIP	= $(CROSS)strip
 SFLAGS	= -R .note -R .comment
+#SFLAGS	= -R .note .comment
 
 CFLAGS	= -W -pthread -Wall -pipe
 CFLAGS	+= -fomit-frame-pointer
@@ -39,7 +42,9 @@ PRGS	= lizard-mt$(EXTENSION) \
 	  lz4-mt$(EXTENSION) \
 	  lz5-mt$(EXTENSION) \
 	  brotli-mt$(EXTENSION) \
-	  zstd-mt$(EXTENSION)
+	  zstd-mt$(EXTENSION) \
+	  snappy-mt$(EXTENSION) \
+	  lzfse-mt$(EXTENSION) 
 
 all:	loadsource $(PRGS)
 again:	clean $(PRGS)
@@ -57,10 +62,18 @@ LIBLZ5	= $(COMMON) $(ZSTDMTDIR)/lz5-mt_common.c $(ZSTDMTDIR)/lz5-mt_compress.c \
 	  $(ZSTDMTDIR)/lz5-mt_decompress.c lz5-mt.c
 LIBZSTD	= $(COMMON) $(ZSTDMTDIR)/zstd-mt_common.c $(ZSTDMTDIR)/zstd-mt_compress.c \
 	  $(ZSTDMTDIR)/zstd-mt_decompress.c zstd-mt.c
+LIBSNAP	= $(COMMON) $(ZSTDMTDIR)/snappy-mt_common.c $(ZSTDMTDIR)/snappy-mt_compress.c \
+	  $(ZSTDMTDIR)/snappy-mt_decompress.c snappy-mt.c
+LIBLZFSE = $(COMMON) $(ZSTDMTDIR)/lzfse-mt_common.c $(ZSTDMTDIR)/lzfse-mt_compress.c \
+	  $(ZSTDMTDIR)/lzfse-mt_decompress.c lzfse-mt.c
 
 # Brotli, https://github.com/google/brotli
 BRODIR	= brotli/c
-LIBBRO	+= $(BRODIR)/common/dictionary.c \
+LIBBRO	+= \
+	  $(BRODIR)/common/constants.c \
+	  $(BRODIR)/common/context.c \
+	  $(BRODIR)/common/dictionary.c \
+	  $(BRODIR)/common/platform.c \
 	  $(BRODIR)/common/transform.c \
 	  $(BRODIR)/dec/bit_reader.c \
 	  $(BRODIR)/dec/decode.c \
@@ -72,19 +85,21 @@ LIBBRO	+= $(BRODIR)/common/dictionary.c \
 	  $(BRODIR)/enc/block_splitter.c \
 	  $(BRODIR)/enc/brotli_bit_stream.c \
 	  $(BRODIR)/enc/cluster.c \
+	  $(BRODIR)/enc/command.c \
 	  $(BRODIR)/enc/compress_fragment.c \
 	  $(BRODIR)/enc/compress_fragment_two_pass.c \
 	  $(BRODIR)/enc/dictionary_hash.c \
 	  $(BRODIR)/enc/encode.c \
 	  $(BRODIR)/enc/encoder_dict.c \
 	  $(BRODIR)/enc/entropy_encode.c \
+	  $(BRODIR)/enc/fast_log.c \
 	  $(BRODIR)/enc/histogram.c \
 	  $(BRODIR)/enc/literal_cost.c \
 	  $(BRODIR)/enc/memory.c \
 	  $(BRODIR)/enc/metablock.c \
 	  $(BRODIR)/enc/static_dict.c \
 	  $(BRODIR)/enc/utf8_util.c
-CF_BRO	= $(CFLAGS) -Ibrotli/include
+CF_BRO	= $(CFLAGS) -I$(BRODIR)/include
 
 # LZ4, https://github.com/Cyan4973/lz4
 LZ4DIR	= lz4/lib
@@ -131,6 +146,9 @@ ZSTDDIR	= zstd/lib
 #	  $(ZSTDDIR)/compress/zstd_lazy.c \
 #	  $(ZSTDDIR)/compress/zstd_ldm.c \
 #	  $(ZSTDDIR)/compress/zstd_opt.c \
+#	  $(ZSTDDIR)/compress/zstd_compress_sequences.c \
+#	  $(ZSTDDIR)/compress/zstd_compress_superblock.c \
+#	  $(ZSTDDIR)/compress/zstd_compress_literals.c \
 #	  $(ZSTDDIR)/decompress/huf_decompress.c \
 #	  $(ZSTDDIR)/decompress/zstd_ddict.c \
 #	  $(ZSTDDIR)/decompress/zstd_decompress.c \
@@ -141,6 +159,22 @@ ZSTDDIR	= zstd/lib
 #	  $(ZSTDDIR)/legacy/zstd_v07.c
 CF_ZSTD	= $(CFLAGS) -I$(ZSTDDIR) -I$(ZSTDDIR)/common -I$(ZSTDDIR)/compress \
 	  -I$(ZSTDDIR)/decompress -I$(ZSTDDIR)/legacy
+
+# snappy-c, https://github.com/andikleen/snappy-c
+SNAPDIR	= snappy
+LIBSNAP	+= $(SNAPDIR)/snappy.c
+CF_SNAP	= $(CFLAGS) -I$(SNAPDIR)
+
+# lzfse, https://github.com/lzfse/lzfse
+LZFSEDIR = lzfse/src
+LIBLZFSE += $(LZFSEDIR)/lzfse_decode.c \
+            $(LZFSEDIR)/lzfse_decode_base.c \
+            $(LZFSEDIR)/lzfse_encode.c \
+            $(LZFSEDIR)/lzfse_encode_base.c \
+            $(LZFSEDIR)/lzfse_fse.c \
+            $(LZFSEDIR)/lzvn_decode_base.c \
+            $(LZFSEDIR)/lzvn_encode_base.c 
+CF_LZFSE = $(CFLAGS) -I$(LZFSEDIR)
 
 # append lib include directory
 CFLAGS	+= -I. -I$(ZSTDMTDIR)
@@ -175,20 +209,45 @@ zstd-mt$(EXTENSION):
 	$(LN) $@ un$@
 	$(LN) $@ zstdcat-mt
 
+snappy-mt$(EXTENSION):
+	$(CC) $(CF_SNAP) -DVERSION='$(SNAP_VER)' -o $@ $(LIBSNAP) $(LDFLAGS)
+	$(STRIP) $(SFLAGS) $@
+	$(LN) $@ un$@
+	$(LN) $@ snappycat-mt
+
+lzfse-mt$(EXTENSION):
+	$(CC) $(CF_LZFSE) -DVERSION='$(LZFSE_VER)' -o $@ $(LIBLZFSE) $(LDFLAGS)
+	$(STRIP) $(SFLAGS) $@
+	$(LN) $@ un$@
+	$(LN) $@ lzfsecat-mt
+
 loadsource:
-	test -d lz4    || git clone https://github.com/Cyan4973/lz4  -b $(LZ4_VER)  --depth=1 lz4
-	test -d lz5    || git clone https://github.com/inikep/lz5    -b $(LZ5_VER)  --depth=1 lz5
-	test -d zstd   || git clone https://github.com/facebook/zstd -b $(ZSTD_VER) --depth=1 zstd
-	test -d lizard || git clone https://github.com/inikep/lizard -b $(LIZ_VER)  --depth=1 lizard
-	test -d brotli || git clone https://github.com/google/brotli -b $(BRO_VER)  --depth=1 brotli
+	test -d lz4    || git clone https://github.com/Cyan4973/lz4       -b $(LZ4_VER)  --depth=1 lz4
+	test -d lz5    || git clone https://github.com/inikep/lz5         -b $(LZ5_VER)  --depth=1 lz5
+	test -d zstd   || git clone https://github.com/facebook/zstd      -b $(ZSTD_VER) --depth=1 zstd
+	test -d lizard || git clone https://github.com/inikep/lizard      -b $(LIZ_VER)  --depth=1 lizard
+	test -d brotli || git clone https://github.com/google/brotli      -b $(BRO_VER)  --depth=1 brotli
+	test -d lzfse  || git clone https://github.com/lzfse/lzfse        -b $(LZFSE_VER) --depth=1 lzfse
+	test -d snappy || git clone https://github.com/andikleen/snappy-c                --depth=1 snappy
+
+# tests are unix / linux only
+tests:
+	@dd if=/dev/urandom of=testbytes.raw bs=1M count=10 2>/dev/null
+	@for m in brotli lizard lz4 lz5 zstd snappy lzfse ; do \
+	cat testbytes.raw | ./$$m-mt -z > compressed.$$m ; \
+	cat compressed.$$m | ./$$m-mt -d > testbytes-$$m.raw ; \
+	cmp testbytes.raw testbytes-$$m.raw && echo "SUCCESS: $$m" || echo "FAILING: $$m" ; \
+	rm compressed.$$m testbytes-$$m.raw ; \
+	done
+	@rm testbytes.raw
 
 install:
 	echo TODO ;)
 
 clean:
 	rm -f $(PRGS)
-	rm -f unbrotli-mt unlizard-mt unlz4-mt unlz5-mt unzstd-mt
-	rm -f brotlicat-mt lizardcat-mt lz4cat-mt lz5cat-mt zstdcat-mt
+	rm -f unbrotli-mt unlizard-mt unlz4-mt unlz5-mt unzstd-mt unsnappy-mt unlzfse-mt
+	rm -f brotlicat-mt lizardcat-mt lz4cat-mt lz5cat-mt zstdcat-mt snappycat-mt lzfsecat-mt
 
 mrproper: clean
-	rm -rf brotli lizard lz4 lz5 zstd
+	rm -rf brotli lizard lz4 lz5 zstd snappy lzfse
